import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b flex gap-6">
          <Link href="/">Home</Link>
          <Link href="/results">results</Link>
          <Link href="/results2">results-2</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
